[features]
seeds = true
[programs.localnet]
sol_raffle = "R4ffL3gDqJ7FqKmL6KjHsGdN5xjG2vV9c9Q7Y8pMnKx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"